###############################################################################
# Tetragon TracingPolicy — 5.6 Nginx RTT
#
# Nginx의 네트워크 경로(accept, sendmsg, recvmsg)를 Tetragon이 트레이싱.
# TCP 연결 수립 및 데이터 전송 경로에서의 오버헤드 측정.
#
# 적용: kubectl apply -f tetragon-policy.yaml
# 제거: kubectl delete -f tetragon-policy.yaml
###############################################################################
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-nginx-tcp-connect
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-nginx-tcp-sendmsg
spec:
  kprobes:
    - call: "tcp_sendmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
        - index: 2
          type: "size_t"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
