###############################################################################
# iperf3 서버 — compute-node-2에 배치
# ClusterIP Service로 클러스터 내부 접근 (port 5201)
###############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server
  namespace: bench-iperf
  labels:
    app: iperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: compute-node-2
      containers:
        - name: iperf3
          image: networkstatic/iperf3
          args: ["-s", "-A", "0"]
          ports:
            - containerPort: 5201
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: "512Mi"
            limits:
              cpu: "4"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 5201
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-svc
  namespace: bench-iperf
spec:
  type: ClusterIP
  selector:
    app: iperf-server
  ports:
    - port: 5201
      targetPort: 5201
      protocol: TCP
