###############################################################################
# iperf3 클라이언트 Pod — compute-node-2에서 장기 실행 (서버와 같은 노드, veth 경로)
# run_bench.sh에서 kubectl exec으로 반복 측정
###############################################################################
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
  namespace: bench-iperf
  labels:
    app: iperf-client
spec:
  nodeSelector:
    kubernetes.io/hostname: compute-node-2
  containers:
    - name: iperf3
      image: networkstatic/iperf3
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: results
          mountPath: /results
  volumes:
    - name: results
      hostPath:
        path: /tmp/2026SoCC/bench-5.6-iperf
        type: DirectoryOrCreate
