###############################################################################
# wrk2 클라이언트 Job — compute-node-1에서 실행
#
# hostPath로 wrk2 바이너리(/opt/bench-tools)와 결과 디렉토리를 마운트
# 환경변수로 RPS, CONNECTIONS, DURATION, SERVER_URL 제어
###############################################################################
apiVersion: batch/v1
kind: Job
metadata:
  name: wrk2-bench
  namespace: bench-nginx
  labels:
    app: wrk2-bench
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: wrk2-bench
    spec:
      nodeSelector:
        kubernetes.io/hostname: compute-node-1
      restartPolicy: Never
      containers:
        - name: wrk2
          image: ubuntu:22.04
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              WRK=/tools/bin/wrk
              RESULT_DIR=/results
              LABEL="${LABEL:-vanilla}"
              TS=$(date +%Y%m%d_%H%M%S)
              THREADS="${THREADS:-4}"
              DURATION="${DURATION:-60s}"
              SERVER_URL="${SERVER_URL:-http://nginx-bench-svc.bench-nginx.svc.cluster.local:80/}"

              echo "=========================================="
              echo "[wrk2] label=${LABEL}"
              echo "[wrk2] server=${SERVER_URL}"
              echo "[wrk2] threads=${THREADS}, duration=${DURATION}"
              echo "=========================================="

              # wrk2 바이너리 확인
              if [ ! -f "${WRK}" ]; then
                echo "[wrk2] ERROR: ${WRK} not found. install_tools.sh 실행 확인"
                exit 1
              fi

              # 서버 연결 확인 (최대 30초 대기)
              echo "[wrk2] 서버 연결 확인 중..."
              for i in $(seq 1 30); do
                if ${WRK} -t1 -c1 -d1s -R1 ${SERVER_URL} > /dev/null 2>&1; then
                  echo "[wrk2] 서버 연결 확인 완료"
                  break
                fi
                sleep 1
              done

              SUMMARY="${RESULT_DIR}/${LABEL}_summary_${TS}.csv"
              echo "label,rps_target,connections,duration,p50_us,p99_us,p999_us,actual_rps,total_requests" > ${SUMMARY}

              # RPS × connections 매트릭스
              for RPS in 1000 5000 10000; do
                for CONNS in 10 50 100 500 1000; do
                  TAG="rps${RPS}_conn${CONNS}"
                  OUTFILE="${RESULT_DIR}/${LABEL}_${TAG}_${TS}.txt"

                  echo ""
                  echo "[wrk2] ── RPS=${RPS}, connections=${CONNS}, duration=${DURATION} ──"

                  ${WRK} \
                    -t ${THREADS} \
                    -c ${CONNS} \
                    -d ${DURATION} \
                    -R ${RPS} \
                    --latency \
                    ${SERVER_URL} \
                    > ${OUTFILE} 2>&1

                  # 결과 파싱
                  P50=$(grep "50.000%" ${OUTFILE} 2>/dev/null | awk '{print $2}' || echo "N/A")
                  P99=$(grep "99.000%" ${OUTFILE} 2>/dev/null | awk '{print $2}' || echo "N/A")
                  P999=$(grep "99.900%" ${OUTFILE} 2>/dev/null | awk '{print $2}' || echo "N/A")
                  ACTUAL=$(grep "Req/Sec" ${OUTFILE} 2>/dev/null | awk '{print $2}' || echo "N/A")
                  TOTAL=$(grep "requests in" ${OUTFILE} 2>/dev/null | awk '{print $1}' || echo "N/A")

                  echo "${LABEL},${RPS},${CONNS},${DURATION},${P50},${P99},${P999},${ACTUAL},${TOTAL}" >> ${SUMMARY}
                  echo "[wrk2] P50=${P50} P99=${P99} P99.9=${P999}"

                  # 쿨다운
                  sleep 5
                done
              done

              echo ""
              echo "[wrk2] ===== 요약 ====="
              cat ${SUMMARY}
              echo "[wrk2] 완료"
          env:
            - name: LABEL
              value: "vanilla"
            - name: THREADS
              value: "4"
            - name: DURATION
              value: "60s"
            - name: SERVER_URL
              value: "http://nginx-bench-svc.bench-nginx.svc.cluster.local:80/"
          volumeMounts:
            - name: tools
              mountPath: /tools
              readOnly: true
            - name: results
              mountPath: /results
      volumes:
        - name: tools
          hostPath:
            path: /opt/bench-tools
            type: DirectoryOrCreate
        - name: results
          hostPath:
            path: /tmp/2026SoCC/bench-5.6
            type: DirectoryOrCreate
