###############################################################################
# 5.7 — ConfigMap + DaemonSet (에이전트 리소스 모니터링용)
#
# 아키텍처:
#   compute-node-1 (클라이언트)
#     ├── bpftrace DaemonSet (privileged, hostPID) — monitor_agent.sh 실행
#     └── ab-client Pod — ab 실행 (03-ab-client-pod.yaml)
#   compute-node-2 (서버)
#     └── Nginx Deployment (02-nginx-deployment.yaml)
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: bpftrace-scripts
  namespace: bench-policy
data:
  trace_connect.bt: |
    tracepoint:syscalls:sys_enter_connect / comm == "lat_connect" / {
        @start[tid] = nsecs;
    }
    tracepoint:syscalls:sys_exit_connect / @start[tid] / {
        $delta = nsecs - @start[tid];
        printf("%llu\n", $delta);
        @latency = hist($delta);
        delete(@start[tid]);
    }
  monitor_agent.sh: |
    #!/usr/bin/env bash
    ###########################################################################
    # monitor_agent.sh — 에이전트 + 노드 CPU/Memory 샘플링 (5.7 Policy Scalability)
    #
    # 수집 항목:
    #   - 에이전트 CPU% (/proc/<pid>/stat utime+stime)
    #   - 에이전트 MEM MB (/proc/<pid>/status VmRSS)
    #   - 노드 전체 CPU% (/proc/stat → 100 - idle%)
    #   - 노드 커널 CPU% (/proc/stat → system + irq + softirq)
    #
    # 인자:
    #   $1 = agent_name    (kloudknox|falco|tetragon)
    #   $2 = interval       (샘플링 간격 초)
    #   $3 = rule_count     (현재 규칙 수)
    #   $4 = output_file    (CSV 출력 경로)
    #
    # CSV: timestamp,rule_count,agent_cpu_pct,agent_mem_mb,node_cpu_pct,node_sys_pct
    ###########################################################################
    set -euo pipefail

    AGENT_NAME="${1:-}"
    INTERVAL="${2:-2}"
    RULE_COUNT="${3:-0}"
    OUTPUT="${4:-/results/monitor.csv}"

    echo "timestamp,rule_count,agent_cpu_pct,agent_mem_mb,node_cpu_pct,node_sys_pct" > "${OUTPUT}"

    # ── 에이전트 PID 탐색 (3단계 폴백) ──────────────────────────────
    AGENT_PID=""
    if [[ -n "${AGENT_NAME}" ]]; then
        AGENT_PID=$(pgrep -x "${AGENT_NAME}" 2>/dev/null | head -1 || true)
        if [[ -z "${AGENT_PID}" ]]; then
            AGENT_PID=$(pgrep -f "/${AGENT_NAME}" 2>/dev/null | head -1 || true)
        fi
        if [[ -z "${AGENT_PID}" ]]; then
            AGENT_PID=$(pgrep -f "${AGENT_NAME}" 2>/dev/null | head -1 || true)
        fi
        if [[ -n "${AGENT_PID}" ]]; then
            echo "[monitor] agent PID: ${AGENT_PID} (${AGENT_NAME})" >&2
        else
            echo "[monitor] agent not found: ${AGENT_NAME}" >&2
        fi
    fi

    # ── 헬퍼 함수 ────────────────────────────────────────────────────
    # /proc/stat → user nice system idle iowait irq softirq steal (8 fields)
    read_cpu_stat() {
        awk '/^cpu / {print $2,$3,$4,$5,$6,$7,$8,$9}' /proc/stat
    }

    read_agent_ticks() {
        local pid="$1"
        if [[ -n "$pid" && -f "/proc/$pid/stat" ]]; then
            awk '{print $14+$15}' "/proc/$pid/stat" 2>/dev/null || echo "0"
        else
            echo "0"
        fi
    }

    read_agent_mem_mb() {
        local pid="$1"
        if [[ -n "$pid" && -f "/proc/$pid/status" ]]; then
            awk '/^VmRSS:/{printf "%.1f",$2/1024}' "/proc/$pid/status" 2>/dev/null || echo "0"
        else
            echo "0"
        fi
    }

    NPROC=$(nproc 2>/dev/null || echo 1)

    echo "[monitor] rule_count=${RULE_COUNT}, agent=${AGENT_NAME:-none}, interval=${INTERVAL}s, nproc=${NPROC}" >&2

    # ── SIGTERM 핸들러 ────────────────────────────────────────────────
    RUNNING=true
    trap 'RUNNING=false' SIGTERM SIGINT

    # ── 초기 스냅샷 ──────────────────────────────────────────────────
    prev_stat=$(read_cpu_stat)
    prev_agent=$(read_agent_ticks "${AGENT_PID}")

    while ${RUNNING}; do
        sleep "${INTERVAL}" || true
        ${RUNNING} || break

        ts=$(date +%Y-%m-%dT%H:%M:%S)
        curr_stat=$(read_cpu_stat)
        curr_agent=$(read_agent_ticks "${AGENT_PID}")

        # 에이전트 CPU% + 노드 CPU%/sys% 를 한번에 계산
        # 입력: prev_agent curr_agent prev_stat(8) curr_stat(8) NPROC
        # /proc/stat fields: user nice system idle iowait irq softirq steal
        read -r agent_cpu node_cpu node_sys <<< $(echo "${prev_agent}" "${curr_agent}" "${prev_stat}" "${curr_stat}" "${NPROC}" | awk '{
            da = $2 - $1

            # prev: $3=user $4=nice $5=sys $6=idle $7=iowait $8=irq $9=softirq $10=steal
            # curr: $11=user $12=nice $13=sys $14=idle $15=iowait $16=irq $17=softirq $18=steal
            pt = $3+$4+$5+$6+$7+$8+$9+$10
            ct = $11+$12+$13+$14+$15+$16+$17+$18
            dt = ct - pt
            nproc = $19

            # agent CPU% (per-core, top style)
            if (dt > 0) acpu = da/dt*100*nproc; else acpu = 0

            # node idle delta
            d_idle = ($14-$6) + ($15-$7)
            # node sys delta (system + irq + softirq)
            d_sys = ($13-$5) + ($16-$8) + ($17-$9)

            if (dt > 0) {
                ncpu = (1 - d_idle/dt) * 100
                nsys = d_sys/dt * 100
            } else {
                ncpu = 0; nsys = 0
            }

            printf "%.2f %.2f %.2f", acpu, ncpu, nsys
        }')

        # 에이전트 메모리 (VmRSS, KB→MB)
        agent_mem=$(read_agent_mem_mb "${AGENT_PID}")

        echo "${ts},${RULE_COUNT},${agent_cpu},${agent_mem},${node_cpu},${node_sys}" >> "${OUTPUT}"

        prev_stat="${curr_stat}"
        prev_agent="${curr_agent}"
    done

    echo "[monitor] stopped → ${OUTPUT}" >&2
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpftrace-tracer
  namespace: bench-policy
  labels:
    app: bpftrace-tracer
spec:
  selector:
    matchLabels:
      app: bpftrace-tracer
  template:
    metadata:
      labels:
        app: bpftrace-tracer
    spec:
      hostPID: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: compute-node-1
      tolerations:
        - operator: Exists
      containers:
        - name: bpftrace
          image: ubuntu:22.04
          command: ["sleep", "infinity"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: results
              mountPath: /results
            - name: kernel-debug
              mountPath: /sys/kernel/debug
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: kernel-headers
              mountPath: /usr/src
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: bpftrace-scripts
        - name: results
          hostPath:
            path: /tmp/2026SoCC/bench-5.7
            type: DirectoryOrCreate
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: modules
          hostPath:
            path: /lib/modules
        - name: kernel-headers
          hostPath:
            path: /usr/src
