###############################################################################
# TCP 서버 Pod — compute-node-1 (localhost 측정용) (5.7)
#
# lmbench bw_tcp -s 를 실행할 장기 실행 Pod.
# 현재 run_bench.sh에서는 workload Pod 내부에서 bw_tcp -s를 실행하고
# 127.0.0.1로 접속하므로, 이 Pod는 사용하지 않음 (참고용).
###############################################################################
apiVersion: v1
kind: Pod
metadata:
  name: tcp-server
  namespace: bench-policy
  labels:
    app: tcp-server
spec:
  nodeSelector:
    kubernetes.io/hostname: compute-node-1
  containers:
    - name: server
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
  volumes:
    - name: tools
      hostPath:
        path: /opt/bench-tools
        type: DirectoryOrCreate
