###############################################################################
# TCP 서버 Pod — boar (미사용, 참고용)
###############################################################################
apiVersion: v1
kind: Pod
metadata:
  name: tcp-server
  namespace: bench-policy
  labels:
    app: tcp-server
spec:
  nodeSelector:
    kubernetes.io/hostname: boar
  containers:
    - name: server
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
  volumes:
    - name: tools
      hostPath:
        path: /opt/bench-tools
        type: DirectoryOrCreate
