###############################################################################
# ab 클라이언트 Pod — compute-node-1에서 장기 실행
# app: workload 라벨 → KloudKnox 정책 매칭용
###############################################################################
apiVersion: v1
kind: Pod
metadata:
  name: ab-client
  namespace: bench-policy
  labels:
    app: workload
spec:
  nodeSelector:
    kubernetes.io/hostname: compute-node-1
  containers:
    - name: ab
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: results
          mountPath: /results
  volumes:
    - name: results
      hostPath:
        path: /tmp/2026SoCC/bench-5.7
        type: DirectoryOrCreate
