###############################################################################
# TCP 서버 Pod — boar (bw_tcp -s, connect 측정용)
###############################################################################
apiVersion: v1
kind: Pod
metadata:
  name: tcp-server
  namespace: bench-syscall
  labels:
    app: tcp-server
spec:
  nodeSelector:
    kubernetes.io/hostname: boar
  containers:
    - name: server
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: tools
          mountPath: /tools
          readOnly: true
  volumes:
    - name: tools
      hostPath:
        path: /opt/bench-tools
        type: DirectoryOrCreate
