###############################################################################
# KloudKnox Policy — 5.6 Nginx RTT
#
# Nginx Pod의 네트워크 트래픽을 KloudKnox가 모니터링하도록 Audit 정책 적용.
# cgroup-BPF 인라인 검증 경로에서의 오버헤드를 측정하기 위함.
#
# 적용: kubectl apply -f kloudknox-policy.yaml
# 제거: kubectl delete -f kloudknox-policy.yaml
###############################################################################
apiVersion: security.boanlab.com/v1
kind: KloudKnoxPolicy
metadata:
  name: bench-nginx-network-audit
  namespace: bench-nginx
spec:
  selector:
    app: nginx-bench
  network:
    - direction: ingress
      ports:
        - protocol: TCP
          port: 80
    - direction: egress
      ipBlock:
        cidr: 10.244.0.0/16
  action: Audit
---
apiVersion: security.boanlab.com/v1
kind: KloudKnoxPolicy
metadata:
  name: bench-nginx-process-audit
  namespace: bench-nginx
spec:
  selector:
    app: nginx-bench
  process:
    - path: /usr/sbin/nginx
    - dir: /usr/bin/
      recursive: false
  action: Audit
---
apiVersion: security.boanlab.com/v1
kind: KloudKnoxPolicy
metadata:
  name: bench-nginx-file-audit
  namespace: bench-nginx
spec:
  selector:
    app: nginx-bench
  file:
    - dir: /etc/nginx/
      recursive: true
      readOnly: true
    - dir: /var/log/nginx/
      recursive: true
    - dir: /usr/share/nginx/html/
      recursive: true
      readOnly: true
  action: Audit
