###############################################################################
# Tetragon TracingPolicy — 5.8 Pod Density
#
# 5.5 (syscall) + 5.6 (nginx) TracingPolicy 합본.
# 중복 제거: execve는 1개로 통합.
#
# 카테고리:
#   1) 네트워크: tcp_connect, inet_csk_accept, tcp_sendmsg, tcp_recvmsg, connect
#   2) 프로세스: __x64_sys_execve (통합)
#   3) 파일: security_file_open, __x64_sys_openat
#
# 적용: kubectl apply -f tetragon-policy.yaml
# 제거: kubectl delete -f tetragon-policy.yaml
###############################################################################
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-density-network
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
    - call: "inet_csk_accept"
      syscall: false
      return: true
      args:
        - index: 0
          type: "sock"
      returnArg:
        index: 0
        type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
    - call: "tcp_sendmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
    - call: "tcp_recvmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
    - call: "__x64_sys_connect"
      syscall: true
      args:
        - index: 1
          type: "sockaddr"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-density-process
spec:
  kprobes:
    - call: "__x64_sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-density-file
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
    - call: "__x64_sys_openat"
      syscall: true
      args:
        - index: 1
          type: "string"
      selectors:
        - matchNamespaces:
            - namespace: Mnt
              operator: NotIn
              values: ["host_ns"]
            - namespace: Pid
              operator: NotIn
              values: ["host_ns"]
