###############################################################################
# KloudKnox Policy — 5.8 Pod Density
#
# 밀도 Pod (busybox)에 대한 일반적인 보안 모니터링 정책.
# Pod 수 증가에 따른 KloudKnox 에이전트의 CPU/Memory 오버헤드를 측정.
# 실제 운영 환경에서의 전형적인 정책 구성을 반영.
#
# 적용: kubectl apply -f kloudknox-policy.yaml
# 제거: kubectl delete -f kloudknox-policy.yaml
###############################################################################
apiVersion: security.boanlab.com/v1
kind: KloudKnoxPolicy
metadata:
  name: bench-density-process-audit
  namespace: bench-density
spec:
  selector:
    app: density-bench
  process:
    - dir: /bin/
      recursive: false
    - dir: /usr/bin/
      recursive: false
  action: Audit
---
apiVersion: security.boanlab.com/v1
kind: KloudKnoxPolicy
metadata:
  name: bench-density-file-audit
  namespace: bench-density
spec:
  selector:
    app: density-bench
  file:
    - dir: /etc/
      recursive: true
      readOnly: true
    - dir: /tmp/
      recursive: true
    - path: /etc/shadow
    - path: /etc/passwd
  action: Audit
---
apiVersion: security.boanlab.com/v1
kind: KloudKnoxPolicy
metadata:
  name: bench-density-network-audit
  namespace: bench-density
spec:
  selector:
    app: density-bench
  network:
    - direction: egress
      ipBlock:
        cidr: 0.0.0.0/0
    - direction: ingress
  action: Audit
