###############################################################################
# Tetragon TracingPolicy — 5.8 Pod Density
#
# 밀도 Pod에 대한 일반적인 시스템 트레이싱 정책.
# Pod 수 증가에 따른 Tetragon의 CPU/Memory 오버헤드를 측정.
# 실제 운영 환경에서의 전형적인 트레이싱 구성을 반영.
#
# 적용: kubectl apply -f tetragon-policy.yaml
# 제거: kubectl delete -f tetragon-policy.yaml
###############################################################################
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-density-process
spec:
  kprobes:
    - call: "__x64_sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-density-file
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-density-network
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
    - call: "inet_csk_accept"
      syscall: false
      return: true
      args:
        - index: 0
          type: "sock"
      returnArg:
        index: 0
        type: "sock"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
