###############################################################################
# Tetragon TracingPolicy — 5.5 Syscall Latency
#
# execve, openat, connect syscall을 Tetragon이 트레이싱하도록 정책 정의.
# kprobe 기반으로 syscall entry를 후킹하여 메타데이터 수집.
# 컨테이너 프로세스만 대상 (호스트 PID 네임스페이스 제외).
#
# 적용: kubectl apply -f tetragon-policy.yaml
# 제거: kubectl delete -f tetragon-policy.yaml
###############################################################################
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-syscall-execve
spec:
  kprobes:
    - call: "__x64_sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-syscall-openat
spec:
  kprobes:
    - call: "__x64_sys_openat"
      syscall: true
      args:
        - index: 1
          type: "string"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: bench-syscall-connect
spec:
  kprobes:
    - call: "__x64_sys_connect"
      syscall: true
      args:
        - index: 1
          type: "sockaddr"
      selectors:
        - matchNamespaces:
            - namespace: Pid
              operator: NotIn
              values:
                - "host_ns"
